/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bioskop;

// GUI Swing
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// Event (misal tombol, tapi di CetakTiket biasanya cuma baca)
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

// Database
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

// Util / List
import java.util.List;
import java.util.ArrayList;

// Koneksi Session + Koneksi DB
import koneksi.Koneksi; // package util Koneksi
import util.Session;    // package util Session


/**
 *
 * @author Lenovo LOQ
 */
public class Cetak_tiket extends javax.swing.JFrame {

    /**
     * Creates new form Cetak_tiket
     */
    public Cetak_tiket() {
        initComponents();
         lblnama.setText(Session.namaPenonton);
        lblfilm1.setText(Session.judulFilm);
        lbltanggal.setText(Session.tanggal);
        lbljam.setText(Session.jam);

    // Isi JTable kursi
    loadKursi();
    
    // hitung harga
    hitungHarga();
    }
    
    private void loadKursi() {
    DefaultTableModel model = (DefaultTableModel) tblKursi.getModel();
    model.setRowCount(0); // kosongkan dulu

    try {
    Connection conn = Koneksi.getConnection();

    for (Integer idKursi : Session.kursiDipilih) {
        String sql = "SELECT nomor_kursi FROM kursi WHERE id_kursi = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, idKursi);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String namaKursi = rs.getString("nomor_kursi");
            model.addRow(new Object[]{namaKursi}); // masukkan ke JTable
        }
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal load kursi: " + e.getMessage());
}

}
    
    private void hitungHarga() {
    int hargaPerTiket;
    String hari = Session.tanggal; // misal: "2026-01-12"

    // cek apakah weekend
    if (hari.equals("2026-01-17") || hari.equals("2026-01-18")) {
        hargaPerTiket = 40000;
    } else {
        hargaPerTiket = 30000;
    }

    int totalHarga = hargaPerTiket * Session.jumlahTiket;
    lblHarga.setText("Rp " + totalHarga);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbljam = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lbltanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKursi = new javax.swing.JTable();
        lblfilm1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 520));
        setPreferredSize(new java.awt.Dimension(400, 520));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("nawira");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 70);

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("cinema");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 0, 198, 70);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("mobile ticket");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 70, 137, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Film");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 70, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 120, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal & Jam");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 110, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Harga");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 450, 70, 20);

        jPanel1.setLayout(null);

        lbljam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbljam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbljam);
        lbljam.setBounds(110, 80, 110, 20);

        lblnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblnama);
        lblnama.setBounds(0, 0, 220, 20);

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblHarga);
        lblHarga.setBounds(0, 330, 220, 20);

        lbltanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbltanggal);
        lbltanggal.setBounds(0, 80, 110, 20);

        tblKursi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "kursi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKursi);
        if (tblKursi.getColumnModel().getColumnCount() > 0) {
            tblKursi.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 220, 200);

        lblfilm1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblfilm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblfilm1);
        lblfilm1.setBounds(0, 40, 220, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 120, 220, 380);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("kursi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cetak_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cetak_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cetak_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cetak_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cetak_tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblfilm1;
    private javax.swing.JLabel lbljam;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lbltanggal;
    private javax.swing.JTable tblKursi;
    // End of variables declaration//GEN-END:variables
}
