/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bioskop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import util.Session;
import koneksi.Koneksi;


/**
 *
 * @author Lenovo LOQ
 */
public class Jumlah_tiket extends javax.swing.JFrame {

    /**
     * Creates new form Jumlah_tiket
     */
    public Jumlah_tiket() {
        initComponents();
    }
    
    private int getSisaKursi(int idJadwal) {
    int sisa = 0;
    try {
        Connection conn = Koneksi.getConnection();

        // 1. Ambil kapasitas studio
        String sql1 = "SELECT s.kapasitas FROM jadwal j JOIN studio s ON j.id_studio = s.id_studio WHERE j.id_jadwal = ?";
        PreparedStatement ps1 = conn.prepareStatement(sql1);
        ps1.setInt(1, idJadwal);
        ResultSet rs1 = ps1.executeQuery();
        if (rs1.next()) {
            sisa = rs1.getInt("kapasitas");
        }

        // 2. Kurangi tiket yang sudah dibooking
        String sql2 = "SELECT COUNT(*) AS terisi FROM tiket WHERE id_jadwal = ?";
        PreparedStatement ps2 = conn.prepareStatement(sql2);
        ps2.setInt(1, idJadwal);
        ResultSet rs2 = ps2.executeQuery();
        if (rs2.next()) {
            sisa -= rs2.getInt("terisi");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal ambil sisa kursi: " + e.getMessage());
    }
    return sisa;
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJumlahTiket = new javax.swing.JTextField();
        btnLanjut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASUKKAN JUMLAH TIKET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 230, 40);

        txtJumlahTiket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJumlahTiket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtJumlahTiket);
        txtJumlahTiket.setBounds(90, 80, 190, 26);

        btnLanjut.setText("Lanjut >>");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLanjut);
        btnLanjut.setBounds(130, 130, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        String strJumlah = txtJumlahTiket.getText().trim();

    if (strJumlah.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah tiket dulu!");
        return;
    }

    int jumlah;
    try {
        jumlah = Integer.parseInt(strJumlah);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah tiket harus angka!");
        return;
    }

    // Ambil sisa kursi untuk jadwal ini
    int sisaKursi = getSisaKursi(Session.idJadwal);

    if (jumlah < 1 || jumlah > sisaKursi) {
        JOptionPane.showMessageDialog(this, "Jumlah tiket harus antara 1 - " + sisaKursi);
        return;
    }

    // simpan ke Session
    Session.jumlahTiket = jumlah;

    // buka Form Studio
    new Studio().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLanjutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jumlah_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jumlah_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jumlah_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jumlah_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jumlah_tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanjut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtJumlahTiket;
    // End of variables declaration//GEN-END:variables
}
