/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bioskop;

import koneksi.Koneksi;
import util.Session;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Pilih_Sore extends javax.swing.JFrame {

    private void setSinopsisSore() {
    deskripsi1.setText("Sore, seorang wanita misterius, datang dari masa depan");
    deskripsi2.setText("ke masa lalu dengan satu misi yaitu");
    deskripsi3.setText("mengubah takdir hidup Jonathan, suaminya.");
    deskripsi4.setText("Namun, segalanya menjadi rumit karena masa lalu, masa kini,");
    deskripsi5.setText("dan masa depan Jonathan bersama Sore menjadi berbenturan.");
  
}
    
    

    /**
     * Creates new form Jadwal
     */
    public Pilih_Sore() {
        initComponents();
        setSinopsisSore();

        Session.idFilm = 7;
        Session.judulFilm = "Sore";
    }
    
    private String getHariDipilih() {
    if (rbsenin.isSelected()) return "2026-01-12";
    if (rbselasa.isSelected()) return "2026-01-13";
    if (rbrabu.isSelected()) return "2026-01-14";
    if (rbkamis.isSelected()) return "2026-01-15";
    if (rbjumat.isSelected()) return "2026-01-16";
    if (rbsabtu.isSelected()) return "2026-01-17";
    if (rbminggu.isSelected()) return "2026-01-18";
    return null;
}
    
    private String getJamDipilih() {
        if (jamke1.isSelected()) return "12:15:00";
        if (jamke2.isSelected()) return "15:00:00";
        if (jamke3.isSelected()) return "17:15:00";
        if (jamke4.isSelected()) return "19:30:00";
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bgHari = new javax.swing.ButtonGroup();
        bgJam = new javax.swing.ButtonGroup();
        deskripsi6 = new javax.swing.JLabel();
        deskripsi7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deskripsi1 = new javax.swing.JLabel();
        deskripsi2 = new javax.swing.JLabel();
        deskripsi3 = new javax.swing.JLabel();
        deskripsi4 = new javax.swing.JLabel();
        deskripsi5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbsenin = new javax.swing.JRadioButton();
        rbselasa = new javax.swing.JRadioButton();
        rbrabu = new javax.swing.JRadioButton();
        rbkamis = new javax.swing.JRadioButton();
        rbjumat = new javax.swing.JRadioButton();
        rbsabtu = new javax.swing.JRadioButton();
        rbminggu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jamke1 = new javax.swing.JRadioButton();
        jamke2 = new javax.swing.JRadioButton();
        jamke3 = new javax.swing.JRadioButton();
        jamke4 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnBelitiket = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jButton2.setText("BUY TICKET");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setPreferredSize(new java.awt.Dimension(84, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("follows the remaining Avengers as they try to reverse Thanos's \nsnap that wiped out half of all life, leading to a desperate \n\"time heist\" to retrieve the Infinity Stones from the past,\nculminating in an epic final battle where they confront Thanos\nand his army, ultimately resulting in Tony Stark's  sacrifice \n to save the universe and Steve Rogers retiring to live a life\n with Peggy Carter. ");
        jScrollPane1.setViewportView(jTextArea1);

        deskripsi6.setText("ultimately resulting in Tony Stark sacrifices to save the universe");

        deskripsi7.setText("and Steve Rogers retiring to live a life with Peggy Carter.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bioskop/Ticket.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("PESAN SEKARANG! AMANKAN KURSIMU!");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("SORE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sinopsis");

        deskripsi1.setText("Sore, seorang wanita misterius, datang dari masa depan");

        deskripsi2.setText("ke masa lalu dengan satu misi yaitu");

        deskripsi3.setText("mengubah takdir hidup Jonathan, suaminya.");

        deskripsi4.setText("Namun, segalanya menjadi rumit karena masa lalu, masa kini,");

        deskripsi5.setText("dan masa depan Jonathan bersama Sore menjadi berbenturan.");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bioskop/Sore.jpg"))); // NOI18N
        jLabel32.setText("jLabel32");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(deskripsi2)
                    .addComponent(deskripsi4)
                    .addComponent(deskripsi3)
                    .addComponent(deskripsi5)
                    .addComponent(deskripsi1))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(275, 275, 275))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deskripsi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deskripsi2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deskripsi3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deskripsi4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deskripsi5))
                    .addComponent(jLabel32))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Hari");

        bgHari.add(rbsenin);
        rbsenin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbsenin.setText("Senin");

        bgHari.add(rbselasa);
        rbselasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbselasa.setText("Selasa");

        bgHari.add(rbrabu);
        rbrabu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbrabu.setText("Rabu");

        bgHari.add(rbkamis);
        rbkamis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbkamis.setText("Kamis");

        bgHari.add(rbjumat);
        rbjumat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbjumat.setText("Jumat");

        bgHari.add(rbsabtu);
        rbsabtu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbsabtu.setText("Sabtu");

        bgHari.add(rbminggu);
        rbminggu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbminggu.setText("Minggu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Jam Tayang");

        bgJam.add(jamke1);
        jamke1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jamke1.setText("12:15");

        bgJam.add(jamke2);
        jamke2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jamke2.setText("15:00");
        jamke2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamke2ActionPerformed(evt);
            }
        });

        bgJam.add(jamke3);
        jamke3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jamke3.setText("17:15");
        jamke3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamke3ActionPerformed(evt);
            }
        });

        bgJam.add(jamke4);
        jamke4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jamke4.setText("19:30");

        jPanel5.setBackground(new java.awt.Color(51, 204, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bioskop/BeliTiket.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        btnBelitiket.setBackground(new java.awt.Color(51, 204, 255));
        btnBelitiket.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBelitiket.setForeground(new java.awt.Color(255, 204, 0));
        btnBelitiket.setText("BELI TIKET");
        btnBelitiket.setBorder(null);
        btnBelitiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelitiketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBelitiket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnBelitiket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbsenin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbselasa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jamke1))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbkamis)
                            .addComponent(rbrabu)
                            .addComponent(jamke2))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbsabtu)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbjumat)
                                    .addComponent(jamke3))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jamke4)
                                    .addComponent(rbminggu))))))
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbjumat)
                        .addComponent(rbminggu))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbsenin)
                        .addComponent(rbrabu)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbselasa)
                    .addComponent(rbkamis)
                    .addComponent(rbsabtu))
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jamke1)
                    .addComponent(jamke2)
                    .addComponent(jamke3)
                    .addComponent(jamke4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jamke2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamke2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamke2ActionPerformed

    private void jamke3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamke3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamke3ActionPerformed

    private void btnBelitiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelitiketActionPerformed
        // TODO add your handling code here:
        String tanggal = getHariDipilih();
    String jam = getJamDipilih();

    if (tanggal == null || jam == null) {
        JOptionPane.showMessageDialog(this, "Pilih hari dan jam dulu!");
        return;
    }

    try {
        Connection conn = Koneksi.getConnection();

        String sql = """
            SELECT id_jadwal, tanggal
            FROM jadwal
            WHERE id_film = ?
              AND tanggal = ?
              AND jam_mulai = ?
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, Session.idFilm);
        ps.setString(2, tanggal);
        ps.setString(3, jam);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            Session.idJadwal = rs.getInt("id_jadwal");
            Session.jam = jam;
            Session.tanggal = rs.getString("tanggal");

            new Jumlah_tiket().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Jadwal tidak ditemukan!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBelitiketActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilih_Sore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilih_Sore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilih_Sore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilih_Sore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilih_Sore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgHari;
    private javax.swing.ButtonGroup bgJam;
    private javax.swing.JButton btnBelitiket;
    private javax.swing.JLabel deskripsi1;
    private javax.swing.JLabel deskripsi2;
    private javax.swing.JLabel deskripsi3;
    private javax.swing.JLabel deskripsi4;
    private javax.swing.JLabel deskripsi5;
    private javax.swing.JLabel deskripsi6;
    private javax.swing.JLabel deskripsi7;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton jamke1;
    private javax.swing.JRadioButton jamke2;
    private javax.swing.JRadioButton jamke3;
    private javax.swing.JRadioButton jamke4;
    private javax.swing.JRadioButton rbjumat;
    private javax.swing.JRadioButton rbkamis;
    private javax.swing.JRadioButton rbminggu;
    private javax.swing.JRadioButton rbrabu;
    private javax.swing.JRadioButton rbsabtu;
    private javax.swing.JRadioButton rbselasa;
    private javax.swing.JRadioButton rbsenin;
    // End of variables declaration//GEN-END:variables
}
