/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bioskop;

import javax.swing.*;          // JButton, JPanel, JOptionPane, JFrame
import java.awt.*;             // Color, Container
import java.awt.event.*;       // ActionListener, ActionEvent

// SQL / Database
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

// Utility
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

// Koneksi & Session
import koneksi.Koneksi;        // class koneksi ke database
import util.Session; 


/**
 *
 * @author Lenovo LOQ
 */
public class Studio extends javax.swing.JFrame {
    
    private Map<JButton, String> tombolKeNama = new HashMap<>(); // tombol → nama kursi (A1..J8)

    private int jumlahTiket;
    
    /**
     * Creates new form Pilih_kursi
     */
    public Studio() {
        initComponents();
        
        jumlahTiket = Session.jumlahTiket;
        String[] baris = {"A","B","C","D","E","F","G","H","I","J"};
        int[] kolom = {1,2,3,4,5,6,7,8};

        for (String b : baris) {
            for (int k : kolom) {
                String nama = b + k;
                try {
                    JButton btn = (JButton) getClass().getDeclaredField(nama.toLowerCase()).get(this);
                    tombolKeNama.put(btn, nama);

                    btn.addActionListener(e -> toggleKursi(btn));

                } catch (Exception ex) {
                    System.out.println("Tombol " + nama + " tidak ditemukan di form");
                }
            }
        }

        loadKursiTerisi();
        

    }
    
    private void toggleKursi(JButton btn) {
        String namaKursi = tombolKeNama.get(btn);
        int idKursiDB = getIdKursi(namaKursi);
        if (!btn.isEnabled() || idKursiDB == -1) return;

        if (Session.kursiDipilih.contains(idKursiDB)) {
            Session.kursiDipilih.remove((Integer) idKursiDB);
            btn.setBackground(Color.LIGHT_GRAY);
        } else {
            if (Session.kursiDipilih.size() < jumlahTiket) {
                Session.kursiDipilih.add(idKursiDB);
                btn.setBackground(Color.GREEN);
            } else {
                JOptionPane.showMessageDialog(this, "Hanya boleh memilih " + jumlahTiket + " kursi.");
            }
        }
    }
    
    private int getIdKursi(String namaKursi) {
        int idKursi = -1;
        try {
            Connection conn = Koneksi.getConnection();
            String sql = """
                SELECT k.id_kursi
                FROM kursi k
                JOIN jadwal j ON k.id_studio = j.id_studio
                WHERE j.id_jadwal = ? AND k.nomor_kursi = ?
            """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Session.idJadwal);
            ps.setString(2, namaKursi);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) idKursi = rs.getInt("id_kursi");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil id kursi: " + e.getMessage());
        }
        return idKursi;
    }
    
    private void loadKursiTerisi() {
        try {
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT k.id_kursi, k.nomor_kursi FROM tiket t JOIN kursi k ON t.id_kursi = k.id_kursi WHERE t.id_jadwal = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, Session.idJadwal);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String namaKursi = rs.getString("nomor_kursi");
                for (Map.Entry<JButton,String> entry : tombolKeNama.entrySet()) {
                    if (entry.getValue().equals(namaKursi)) {
                        JButton btn = entry.getKey();
                        btn.setBackground(Color.RED);
                        btn.setEnabled(false);
                        break;
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load kursi: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a6 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        d6 = new javax.swing.JButton();
        e6 = new javax.swing.JButton();
        f6 = new javax.swing.JButton();
        g6 = new javax.swing.JButton();
        h6 = new javax.swing.JButton();
        i6 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        i5 = new javax.swing.JButton();
        h5 = new javax.swing.JButton();
        g5 = new javax.swing.JButton();
        f5 = new javax.swing.JButton();
        e5 = new javax.swing.JButton();
        d5 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        i8 = new javax.swing.JButton();
        h8 = new javax.swing.JButton();
        g8 = new javax.swing.JButton();
        f8 = new javax.swing.JButton();
        e8 = new javax.swing.JButton();
        d8 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        i7 = new javax.swing.JButton();
        h7 = new javax.swing.JButton();
        g7 = new javax.swing.JButton();
        f7 = new javax.swing.JButton();
        e7 = new javax.swing.JButton();
        d7 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        i4 = new javax.swing.JButton();
        h4 = new javax.swing.JButton();
        g4 = new javax.swing.JButton();
        f4 = new javax.swing.JButton();
        e4 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        i3 = new javax.swing.JButton();
        h3 = new javax.swing.JButton();
        g3 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        i2 = new javax.swing.JButton();
        h2 = new javax.swing.JButton();
        g2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        i1 = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Studio 1");
        setPreferredSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAYAR");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 18));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 560, 26);

        a6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a6.setText("A6");
        a6.setMaximumSize(new java.awt.Dimension(20, 20));
        a6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a6);
        a6.setBounds(190, 485, 50, 40);

        b6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b6.setText("B6");
        b6.setMaximumSize(new java.awt.Dimension(20, 20));
        b6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b6);
        b6.setBounds(190, 440, 50, 40);

        c6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c6.setText("C6");
        c6.setMaximumSize(new java.awt.Dimension(20, 20));
        c6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c6);
        c6.setBounds(190, 395, 50, 40);

        d6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d6.setText("D6");
        d6.setMaximumSize(new java.awt.Dimension(20, 20));
        d6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d6);
        d6.setBounds(190, 350, 50, 40);

        e6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e6.setText("E6");
        e6.setMaximumSize(new java.awt.Dimension(20, 20));
        e6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e6);
        e6.setBounds(190, 305, 50, 40);

        f6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f6.setText("F6");
        f6.setMaximumSize(new java.awt.Dimension(20, 20));
        f6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f6);
        f6.setBounds(190, 260, 50, 40);

        g6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g6.setText("G6");
        g6.setMaximumSize(new java.awt.Dimension(20, 20));
        g6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g6);
        g6.setBounds(190, 215, 50, 40);

        h6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h6.setText("H6");
        h6.setMaximumSize(new java.awt.Dimension(20, 20));
        h6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h6);
        h6.setBounds(190, 170, 50, 40);

        i6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i6.setText("I6");
        i6.setMaximumSize(new java.awt.Dimension(20, 20));
        i6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i6);
        i6.setBounds(190, 125, 50, 40);

        j6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j6.setText("J6");
        j6.setMaximumSize(new java.awt.Dimension(20, 20));
        j6.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j6);
        j6.setBounds(190, 80, 50, 40);

        j5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j5.setText("J5");
        j5.setMaximumSize(new java.awt.Dimension(20, 20));
        j5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j5);
        j5.setBounds(250, 80, 50, 40);

        i5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i5.setText("I5");
        i5.setMaximumSize(new java.awt.Dimension(20, 20));
        i5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i5);
        i5.setBounds(250, 125, 50, 40);

        h5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h5.setText("H5");
        h5.setMaximumSize(new java.awt.Dimension(20, 20));
        h5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h5);
        h5.setBounds(250, 170, 50, 40);

        g5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g5.setText("G5");
        g5.setMaximumSize(new java.awt.Dimension(20, 20));
        g5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g5);
        g5.setBounds(250, 215, 50, 40);

        f5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f5.setText("F5");
        f5.setMaximumSize(new java.awt.Dimension(20, 20));
        f5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f5);
        f5.setBounds(250, 260, 50, 40);

        e5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e5.setText("E5");
        e5.setMaximumSize(new java.awt.Dimension(20, 20));
        e5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e5);
        e5.setBounds(250, 305, 50, 40);

        d5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d5.setText("D5");
        d5.setMaximumSize(new java.awt.Dimension(20, 20));
        d5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d5);
        d5.setBounds(250, 350, 50, 40);

        c5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c5.setText("C5");
        c5.setMaximumSize(new java.awt.Dimension(20, 20));
        c5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c5);
        c5.setBounds(250, 395, 50, 40);

        b5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b5.setText("B5");
        b5.setMaximumSize(new java.awt.Dimension(20, 20));
        b5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b5);
        b5.setBounds(250, 440, 50, 40);

        a5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a5.setText("A5");
        a5.setMaximumSize(new java.awt.Dimension(20, 20));
        a5.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a5);
        a5.setBounds(250, 485, 50, 40);

        j8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j8.setText("J8");
        j8.setMaximumSize(new java.awt.Dimension(20, 20));
        j8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j8);
        j8.setBounds(10, 80, 50, 40);

        i8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i8.setText("I8");
        i8.setMaximumSize(new java.awt.Dimension(20, 20));
        i8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i8);
        i8.setBounds(10, 125, 50, 40);

        h8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h8.setText("H8");
        h8.setMaximumSize(new java.awt.Dimension(20, 20));
        h8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h8);
        h8.setBounds(10, 170, 50, 40);

        g8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g8.setText("G8");
        g8.setMaximumSize(new java.awt.Dimension(20, 20));
        g8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g8);
        g8.setBounds(10, 215, 50, 40);

        f8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f8.setText("F8");
        f8.setMaximumSize(new java.awt.Dimension(20, 20));
        f8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f8);
        f8.setBounds(10, 260, 50, 40);

        e8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e8.setText("E8");
        e8.setMaximumSize(new java.awt.Dimension(20, 20));
        e8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e8);
        e8.setBounds(10, 305, 50, 40);

        d8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d8.setText("D8");
        d8.setMaximumSize(new java.awt.Dimension(20, 20));
        d8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d8);
        d8.setBounds(10, 350, 50, 40);

        c8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c8.setText("C8");
        c8.setMaximumSize(new java.awt.Dimension(20, 20));
        c8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c8);
        c8.setBounds(10, 395, 50, 40);

        b8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b8.setText("B1");
        b8.setMaximumSize(new java.awt.Dimension(20, 20));
        b8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b8);
        b8.setBounds(10, 440, 50, 40);

        a8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a8.setText("A8");
        a8.setMaximumSize(new java.awt.Dimension(20, 20));
        a8.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a8);
        a8.setBounds(10, 485, 50, 40);

        j7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j7.setText("J7");
        j7.setMaximumSize(new java.awt.Dimension(20, 20));
        j7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j7);
        j7.setBounds(70, 80, 50, 40);

        i7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i7.setText("I7");
        i7.setMaximumSize(new java.awt.Dimension(20, 20));
        i7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i7);
        i7.setBounds(70, 125, 50, 40);

        h7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h7.setText("H7");
        h7.setMaximumSize(new java.awt.Dimension(20, 20));
        h7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h7);
        h7.setBounds(70, 170, 50, 40);

        g7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g7.setText("G7");
        g7.setMaximumSize(new java.awt.Dimension(20, 20));
        g7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g7);
        g7.setBounds(70, 215, 50, 40);

        f7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f7.setText("F7");
        f7.setMaximumSize(new java.awt.Dimension(20, 20));
        f7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f7);
        f7.setBounds(70, 260, 50, 40);

        e7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e7.setText("E7");
        e7.setMaximumSize(new java.awt.Dimension(20, 20));
        e7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e7);
        e7.setBounds(70, 305, 50, 40);

        d7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d7.setText("D7");
        d7.setMaximumSize(new java.awt.Dimension(20, 20));
        d7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d7);
        d7.setBounds(70, 350, 50, 40);

        c7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c7.setText("C7");
        c7.setMaximumSize(new java.awt.Dimension(20, 20));
        c7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c7);
        c7.setBounds(70, 395, 50, 40);

        b7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b7.setText("B7");
        b7.setMaximumSize(new java.awt.Dimension(20, 20));
        b7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b7);
        b7.setBounds(70, 440, 50, 40);

        a7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a7.setText("A7");
        a7.setMaximumSize(new java.awt.Dimension(20, 20));
        a7.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a7);
        a7.setBounds(70, 485, 50, 40);

        j4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j4.setText("J4");
        j4.setMaximumSize(new java.awt.Dimension(20, 20));
        j4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j4);
        j4.setBounds(310, 80, 50, 40);

        i4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i4.setText("I4");
        i4.setMaximumSize(new java.awt.Dimension(20, 20));
        i4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i4);
        i4.setBounds(310, 125, 50, 40);

        h4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h4.setText("H4");
        h4.setMaximumSize(new java.awt.Dimension(20, 20));
        h4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h4);
        h4.setBounds(310, 170, 50, 40);

        g4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g4.setText("G4");
        g4.setMaximumSize(new java.awt.Dimension(20, 20));
        g4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g4);
        g4.setBounds(310, 215, 50, 40);

        f4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f4.setText("F4");
        f4.setMaximumSize(new java.awt.Dimension(20, 20));
        f4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f4);
        f4.setBounds(310, 260, 50, 40);

        e4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e4.setText("E4");
        e4.setMaximumSize(new java.awt.Dimension(20, 20));
        e4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e4);
        e4.setBounds(310, 305, 50, 40);

        d4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d4.setText("D4");
        d4.setMaximumSize(new java.awt.Dimension(20, 20));
        d4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d4);
        d4.setBounds(310, 350, 50, 40);

        c4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c4.setText("C4");
        c4.setMaximumSize(new java.awt.Dimension(20, 20));
        c4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c4);
        c4.setBounds(310, 395, 50, 40);

        b4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b4.setText("B4");
        b4.setMaximumSize(new java.awt.Dimension(20, 20));
        b4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b4);
        b4.setBounds(310, 440, 50, 40);

        a4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a4.setText("A4");
        a4.setMaximumSize(new java.awt.Dimension(20, 20));
        a4.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a4);
        a4.setBounds(310, 485, 50, 40);

        j3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j3.setText("J3");
        j3.setMaximumSize(new java.awt.Dimension(20, 20));
        j3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j3);
        j3.setBounds(370, 80, 50, 40);

        i3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i3.setText("I3");
        i3.setMaximumSize(new java.awt.Dimension(20, 20));
        i3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i3);
        i3.setBounds(370, 125, 50, 40);

        h3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h3.setText("H3");
        h3.setMaximumSize(new java.awt.Dimension(20, 20));
        h3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h3);
        h3.setBounds(370, 170, 50, 40);

        g3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g3.setText("G3");
        g3.setMaximumSize(new java.awt.Dimension(20, 20));
        g3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g3);
        g3.setBounds(370, 215, 50, 40);

        f3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f3.setText("F3");
        f3.setMaximumSize(new java.awt.Dimension(20, 20));
        f3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f3);
        f3.setBounds(370, 260, 50, 40);

        e3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e3.setText("E3");
        e3.setMaximumSize(new java.awt.Dimension(20, 20));
        e3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e3);
        e3.setBounds(370, 305, 50, 40);

        d3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d3.setText("D3");
        d3.setMaximumSize(new java.awt.Dimension(20, 20));
        d3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d3);
        d3.setBounds(370, 350, 50, 40);

        c3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c3.setText("C3");
        c3.setMaximumSize(new java.awt.Dimension(20, 20));
        c3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c3);
        c3.setBounds(370, 395, 50, 40);

        b3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b3.setText("B3");
        b3.setMaximumSize(new java.awt.Dimension(20, 20));
        b3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b3);
        b3.setBounds(370, 440, 50, 40);

        a3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a3.setText("A3");
        a3.setMaximumSize(new java.awt.Dimension(20, 20));
        a3.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a3);
        a3.setBounds(370, 485, 50, 40);

        j2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j2.setText("J2");
        j2.setMaximumSize(new java.awt.Dimension(20, 20));
        j2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j2);
        j2.setBounds(490, 80, 50, 40);

        i2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i2.setText("I2");
        i2.setMaximumSize(new java.awt.Dimension(20, 20));
        i2.setPreferredSize(new java.awt.Dimension(50, 40));
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });
        getContentPane().add(i2);
        i2.setBounds(490, 125, 50, 40);

        h2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h2.setText("H2");
        h2.setMaximumSize(new java.awt.Dimension(20, 20));
        h2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h2);
        h2.setBounds(490, 170, 50, 40);

        g2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g2.setText("G2");
        g2.setMaximumSize(new java.awt.Dimension(20, 20));
        g2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g2);
        g2.setBounds(490, 215, 50, 40);

        f2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f2.setText("F2");
        f2.setMaximumSize(new java.awt.Dimension(20, 20));
        f2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f2);
        f2.setBounds(490, 260, 50, 40);

        e2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e2.setText("E2");
        e2.setMaximumSize(new java.awt.Dimension(20, 20));
        e2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e2);
        e2.setBounds(490, 305, 50, 40);

        d2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d2.setText("D2");
        d2.setMaximumSize(new java.awt.Dimension(20, 20));
        d2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d2);
        d2.setBounds(490, 350, 50, 40);

        c2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c2.setText("C2");
        c2.setMaximumSize(new java.awt.Dimension(20, 20));
        c2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c2);
        c2.setBounds(490, 395, 50, 40);

        b2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b2.setText("B2");
        b2.setMaximumSize(new java.awt.Dimension(20, 20));
        b2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b2);
        b2.setBounds(490, 440, 50, 40);

        a2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a2.setText("A2");
        a2.setMaximumSize(new java.awt.Dimension(20, 20));
        a2.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a2);
        a2.setBounds(490, 485, 50, 40);

        j1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        j1.setText("J1");
        j1.setMaximumSize(new java.awt.Dimension(20, 20));
        j1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(j1);
        j1.setBounds(550, 80, 50, 40);

        i1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        i1.setText("I1");
        i1.setMaximumSize(new java.awt.Dimension(20, 20));
        i1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(i1);
        i1.setBounds(550, 125, 50, 40);

        h1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        h1.setText("H1");
        h1.setMaximumSize(new java.awt.Dimension(20, 20));
        h1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(h1);
        h1.setBounds(550, 170, 50, 40);

        g1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        g1.setText("G1");
        g1.setMaximumSize(new java.awt.Dimension(20, 20));
        g1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(g1);
        g1.setBounds(550, 215, 50, 40);

        f1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        f1.setText("F1");
        f1.setMaximumSize(new java.awt.Dimension(20, 20));
        f1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(f1);
        f1.setBounds(550, 260, 50, 40);

        e1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        e1.setText("E1");
        e1.setMaximumSize(new java.awt.Dimension(20, 20));
        e1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(e1);
        e1.setBounds(550, 305, 50, 40);

        d1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        d1.setText("D1");
        d1.setMaximumSize(new java.awt.Dimension(20, 20));
        d1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(d1);
        d1.setBounds(550, 350, 50, 40);

        c1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        c1.setText("C1");
        c1.setMaximumSize(new java.awt.Dimension(20, 20));
        c1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(c1);
        c1.setBounds(550, 395, 50, 40);

        b1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        b1.setText("B1");
        b1.setMaximumSize(new java.awt.Dimension(20, 20));
        b1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(b1);
        b1.setBounds(550, 440, 50, 40);

        a1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        a1.setText("A1");
        a1.setMaximumSize(new java.awt.Dimension(20, 20));
        a1.setPreferredSize(new java.awt.Dimension(50, 40));
        getContentPane().add(a1);
        a1.setBounds(550, 485, 50, 40);

        btnCetak.setText("Cetak Tiket");
        btnCetak.setPreferredSize(new java.awt.Dimension(110, 50));
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak);
        btnCetak.setBounds(490, 560, 110, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i2ActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if (Session.kursiDipilih.size() != jumlahTiket) {
            JOptionPane.showMessageDialog(this, "Harus memilih " + jumlahTiket + " kursi!");
            return;
        }

        try {
            Connection conn = Koneksi.getConnection();
            String sql = "INSERT INTO tiket (id_jadwal, id_kursi, status) VALUES (?, ?, 'Booked')";
            PreparedStatement ps = conn.prepareStatement(sql);

            for (int idKursi : Session.kursiDipilih) {
                ps.setInt(1, Session.idJadwal);
                ps.setInt(2, idKursi);
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Tiket berhasil dicetak!");
            new Cetak_tiket().setVisible(true);
            this.dispose(); // lanjut ke form cetak tiket 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan tiket: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton d4;
    private javax.swing.JButton d5;
    private javax.swing.JButton d6;
    private javax.swing.JButton d7;
    private javax.swing.JButton d8;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton e4;
    private javax.swing.JButton e5;
    private javax.swing.JButton e6;
    private javax.swing.JButton e7;
    private javax.swing.JButton e8;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton f4;
    private javax.swing.JButton f5;
    private javax.swing.JButton f6;
    private javax.swing.JButton f7;
    private javax.swing.JButton f8;
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton g3;
    private javax.swing.JButton g4;
    private javax.swing.JButton g5;
    private javax.swing.JButton g6;
    private javax.swing.JButton g7;
    private javax.swing.JButton g8;
    private javax.swing.JButton h1;
    private javax.swing.JButton h2;
    private javax.swing.JButton h3;
    private javax.swing.JButton h4;
    private javax.swing.JButton h5;
    private javax.swing.JButton h6;
    private javax.swing.JButton h7;
    private javax.swing.JButton h8;
    private javax.swing.JButton i1;
    private javax.swing.JButton i2;
    private javax.swing.JButton i3;
    private javax.swing.JButton i4;
    private javax.swing.JButton i5;
    private javax.swing.JButton i6;
    private javax.swing.JButton i7;
    private javax.swing.JButton i8;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
